-- DataBae schema (PostgreSQL)
-- entity sets only for now, relationships come later

CREATE TABLE users (
    email       VARCHAR(255) PRIMARY KEY,
    verified    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE profile (
    uni          VARCHAR(10) PRIMARY KEY,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    gender       VARCHAR(30),
    school_year  VARCHAR(20)
);

CREATE TABLE status (
    sid           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status        VARCHAR(30) NOT NULL,
    status_basis  VARCHAR(50),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE report (
    rid            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       VARCHAR(30) NOT NULL,
    report_reason  VARCHAR(500),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
