-- DataBae schema (PostgreSQL)
-- entity sets only for now, relationships come later

CREATE TABLE users (
    email       VARCHAR(255) PRIMARY KEY,
    verified    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE profile (
    uni          VARCHAR(10) PRIMARY KEY,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    gender       VARCHAR(30),
    school_year  VARCHAR(20)
);

CREATE TABLE status (
    sid           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status        VARCHAR(30) NOT NULL,
    status_basis  VARCHAR(50),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE report (
    rid            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       VARCHAR(30) NOT NULL,
    report_reason  VARCHAR(500),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department (
    name           VARCHAR(100) PRIMARY KEY,
    housed_at      VARCHAR(100),
    offered_major  BOOLEAN NOT NULL DEFAULT FALSE,
    offered_minor  BOOLEAN NOT NULL DEFAULT FALSE
);

-- call numbers are per section per term, so term is part of the key
CREATE TABLE class_section (
    call_number  VARCHAR(10) NOT NULL,
    term         VARCHAR(20) NOT NULL,
    course_name  VARCHAR(200) NOT NULL,
    professor    VARCHAR(100),
    PRIMARY KEY (call_number, term)
);
