CREATE TABLE users (
    email       VARCHAR(255) PRIMARY KEY
                CHECK (email = LOWER(email) AND email LIKE '%@columbia.edu'),
    verified    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE profile (
    uni          VARCHAR(10) PRIMARY KEY
                 CHECK (uni ~ '^[a-z]{2,3}[0-9]{1,4}$'),
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    gender       VARCHAR(30),
    school_year  VARCHAR(20)
                 CHECK (school_year IN ('first-year', 'sophomore', 'junior', 'senior', 'graduate'))
);

CREATE TABLE status (
    sid           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status        VARCHAR(30) NOT NULL
                  CHECK (status IN ('single', 'in_relationship', 'not_looking')),
    status_basis  VARCHAR(50)
                  CHECK (status_basis IN ('told_directly', 'knows_personally', 'recently_dated',
                                          'public_statement', 'other')),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE report (
    rid            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       VARCHAR(30) NOT NULL
                   CHECK (category IN ('false_info', 'abusive', 'inappropriate', 'other')),
    report_reason  VARCHAR(500),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department (
    name           VARCHAR(100) PRIMARY KEY,
    housed_at      VARCHAR(100),
    offered_major  BOOLEAN NOT NULL DEFAULT FALSE,
    offered_minor  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE class_section (
    call_number  VARCHAR(10) NOT NULL CHECK (call_number ~ '^[0-9]{5}$'),
    term         VARCHAR(20) NOT NULL CHECK (term ~ '^(Spring|Summer|Fall) [0-9]{4}$'),
    course_name  VARCHAR(200) NOT NULL,
    professor    VARCHAR(100),
    PRIMARY KEY (call_number, term)
);
